#!/bin/sh

current_path=$(pwd)
ln_flags="-sfn"

link_with_flags () {
    ln "$ln_flags" "$1" "$2"
}

# for when path relative to this folder is the same as path relative to $HOME
link_same() {
  path=$1
  link_with_flags "$current_path/$path" "$HOME/$path"
}

emacs_dir=".emacs.d"
cp "$current_path/$emacs_dir/early-init.el" "$HOME/$emacs_dir/early-init.el"
link_same "$emacs_dir/init.el"
# link_same "$emacs_dir/snippets"

config_dir=".config"
link_same "$config_dir/alacritty"
link_same "$config_dir/iterm2"
link_same "$config_dir/helix"
link_same "$config_dir/zathura"
link_same "$config_dir/nvim"
link_same "$config_dir/zellij"
link_same "$config_dir/lazygit"
link_same "$config_dir/ghostty"

org_path="zsh"
link_same ".zshenv"
link_same ".hushlogin"
link_same ".zsh"
link_same ".tmux.conf"
link_same ".latexmkrc"
link_same ".vim"

org_path="browsers/firefox/"
file="userChrome.css"

# more complex ones do directly
link_with_flags "$current_path/$org_path/$file" "$HOME/Library/Application Support/Firefox/Profiles/xecm18k5.default-release/chrome/$file"
link_with_flags "$current_path/browsers/qutebrowser" "$HOME/.qutebrowser"
link_with_flags "$current_path/obsidian" "$HOME/Documents/Vault/.obsidian/snippets"

# latex
texmf_home=$(kpsewhich -var-value TEXMFHOME)
link_with_flags "$current_path/texmf" "$texmf_home"
