[manager]
show_hidden = true
ratio = [2, 2, 4]

[plugin]
prepend_previewers = [
    { mime = "image/*", run = "noop" } # image preview doesn't work in tmux popups which is usually how I utilize with yazi
]
