#!/usr/bin/env zsh

popup=false
editor_args=()

for arg; do
    [[ $arg == --popup ]] && popup=true || editor_args+=("$arg")
done

if $popup; then
    $EDITOR -c 'set laststatus=0 | set showtabline=0' "${editor_args[@]}"
else
    $EDITOR "${editor_args[@]}"
fi
