#!/usr/bin/env zsh

popup=false
editor_args=()
original_pane_name=""
org=false

for arg in "$@"; do
    if [[ $arg == --popup ]]; then
        popup=true
    else
        editor_args+=("$arg")
    fi

    if [[ $arg == *.org ]]; then
        org=true
    fi
done

# commented region from when trying to support TMUX window naming by process
# if [ -n "$TMUX" ]; then
#     original_pane_name=$(tmux display-message -p '#W')
#     tmux rename-window "$EDITOR"
# fi

if $org; then
    echo $SET_INSERT_CURSOR
    $NOTES_EDITOR "${editor_args[@]}"
else
    if $popup; then
        $EDITOR -c 'set laststatus=0 showtabline=0 nonumber norelativenumber signcolumn=no' "${editor_args[@]}"
    else
        $EDITOR "${editor_args[@]}"
    fi
fi

# if [ -n "$original_pane_name" ]; then
#     tmux rename-window "$original_pane_name"
# fi
