#!/usr/bin/env zsh

local popup=false
local fzf_args=""
local dir=""
for arg; do
    case $arg in
        --popup)
            fzf_args="--height 100% --border none"
            popup=true
            ;;
        *)
            dir=$arg
            ;;
    esac
done

local selected
if [ -z "$dir" ]; then
    # TODO use the pipe here make sure it works
    selected=$(fzf $(echo "$fzf_args" | tr -d '"'))
else
    selected=$(eval "$FZF_DEFAULT_COMMAND '$dir'" | fzf $(echo "$fzf_args" | tr -d '"'))
fi

if [ -n "$selected" ]; then
    if $popup; then
        e --popup "$selected"
    else
        e "$selected"
    fi
fi
