#!/usr/bin/env zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Projects ~/Documents/applications -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_has_session=f
if tmux has-session -t $selected_name 2> /dev/null; then
    tmux_has_session=t
fi

if [ -z $TMUX ]; then
    if [ $tmux_has_session = t ]; then
        tmux attach-session -t $selected_name
    else
        tmux new-session -s $selected_name -c $selected
    fi
    exit 0
fi

if [ -n $TMUX ] && [ $tmux_has_session = f ]; then
    tmux new-session -d -s $selected_name -c $selected
fi
tmux switch-client -t $selected_name
