#!/usr/bin/env zsh

local fzf_args=""
local given=""
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --popup)
            fzf_args="--height 100% --border none"
            shift
            ;;
        *)
            given=$1
            shift
            ;;
    esac
done

local selected
if [[ -n "$given" ]]; then
    selected="$given"
else
    paths="~/Projects ~/Documents/org ~/Documents/research ~/Documents/applications ~/Documents/school"
    poss="find $paths -mindepth 0 -maxdepth 1 -type d -not -name '.git'"
    selected=$(eval 'echo $HOME; '${poss}'' | fzf $(echo "$fzf_args" | tr -d '"'))
fi

if [[ -z $selected ]]; then
    exit 0
fi

local selected_name=$(basename "$selected" | tr . _)
local tmux_has_session=f
if tmux has-session -t $selected_name 2> /dev/null; then
    tmux_has_session=t
fi

if [ -z $TMUX ]; then
    if [ $tmux_has_session = t ]; then
        tmux attach-session -t $selected_name
    else
        tmux new-session -s $selected_name -c $selected
    fi
    exit 0
fi

if [ -n $TMUX ] && [ $tmux_has_session = f ]; then
    tmux new-session -d -s $selected_name -c $selected
fi
tmux switch-client -t $selected_name
