import = ["/Users/timothy/.config/alacritty/everforest.toml"]

[env]
TERM = "xterm-256color"

[cursor]
thickness = 0.3

[font]
size = 18.0

[font.normal]
family = "mononoki"

[window]
decorations = "buttonless"
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
