import = ["~/.config/alacritty/catppuccin_frappe.toml"]

[env]
TERM = "xterm-256color"

[cursor]
thickness = 0.3

[font]
size = 20.0

[font.normal]
family = "Mononoki Nerd Font"

[window]
decorations = "buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"
dynamic_padding = true

[window.padding]
x = 5
y = 5
