import = ["~/.config/alacritty/catppuccin_mocha.toml"]

[env]
TERM = "alacritty"

[cursor]
thickness = 0.3

[font]
size = 15

[font.normal]
family = "RecMonoCasual Nerd Font"

[window]
decorations = "buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 5
y = 5
