[colors.primary]
background = '#303446'
foreground = '#C6D0F5'
dim_foreground = '#C6D0F5'
bright_foreground = '#C6D0F5'

[colors.cursor]
text = '#303446'
cursor = '#F2D5CF'

[colors.normal]
black = '#51576D'
red = '#E78284'
green = '#A6D189'
yellow = '#E5C890'
blue = '#8CAAEE'
magenta = '#F4B8E4'
cyan = '#81C8BE'
white = '#B5BFE2'

[colors.bright]
black = '#626880'
red = '#E78284'
green = '#A6D189'
yellow = '#E5C890'
blue = '#8CAAEE'
magenta = '#F4B8E4'
cyan = '#81C8BE'
white = '#A5ADCE'

[colors.dim]
black = '#51576D'
red = '#E78284'
green = '#A6D189'
yellow = '#E5C890'
blue = '#8CAAEE'
magenta = '#F4B8E4'
cyan = '#81C8BE'
white = '#B5BFE2'
