# TODO when quitting helix, the editor from above the prompt it was launched with still show
# TODO after opening a insert-output mouse no longer works
theme = 'catppuccin_latte'

[editor]
line-number = 'relative'
mouse = true
auto-pairs = false
bufferline = 'always'

[editor.cursor-shape]
normal = 'block'
insert = 'underline'
select = 'underline'

[editor.file-picker]
hidden = false

[editor.statusline]
left = ['spacer', 'file-type', 'spacer', 'version-control', 'spinner']
center = ['file-name', 'file-line-ending']
right = ['diagnostics', 'position', 'position-percentage', 'spacer']

[editor.indent-guides]
render = true
character = '|'

[editor.soft-wrap]
enable = true
wrap-indicator = ''

[keys.normal]
minus = 'repeat_last_motion'
C-g = [
    ':write-all',
    ':new',
    ':insert-output lg',
    ':buffer-close!',
    ':redraw',
    ':reload-all'
]
C-y = [
    ':sh rm -f /tmp/unique-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
    ':open %sh{cat /tmp/unique-file}',
    ':redraw',
]

[keys.normal.g]
x = ':buffer-close'
