theme = 'catppuccin_latte'

[editor]
line-number = 'relative'
mouse = true
auto-pairs = false
bufferline = 'always'

[editor.cursor-shape]
normal = 'block'
insert = 'underline'
select = 'underline'

[editor.file-picker]
hidden = false

[editor.statusline]
left = ['spacer', 'file-type', 'spacer', 'version-control', 'spinner']
center = ['file-name', 'file-line-ending']
right = ['diagnostics', 'position', 'position-percentage', 'spacer']

[editor.indent-guides]
render = true
character = '|'

[editor.soft-wrap]
enable = true
wrap-indicator = ''

[keys.normal]
minus = 'repeat_last_motion'
C-g = [
    ':write-all',
    ':new',
    ':insert-output lg',
    ':buffer-close!',
    ':redraw',
    ':reload-all',
    ':set mouse false',
    ':set mouse true',
]
C-y = [
    ':sh rm -f /tmp/unique-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
    ':open %sh{cat /tmp/unique-file}',
    ':redraw',
    ':set mouse false',
    ':set mouse true',
]
C-r = [
    ':sh rm -f /tmp/tgrep-select',
    ':insert-output tgrep --menu --selection-file=/tmp/tgrep-select --repeat-file=/tmp/tgrep-repeat > /dev/tty',
    ':open %sh{ f=$(sed -n 1p /tmp/tgrep-select); l=$(sed -n 2p /tmp/tgrep-select); [ -n "$l" ] && echo "$f:$l" || echo "$f"; }',
    ':redraw',
    ':set mouse false',
    ':set mouse true',
]

[keys.normal.g]
x = ':buffer-close'
